<a href="https://colab.research.google.com/github/dineshkalal/ML/blob/main/decision_tree_ran_for.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score



In [ ]:
data = pd.read_csv('/content/iris.csv')
data


sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [ ]:
X = data.iloc[:,0:4].values
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [ ]:
type(X)

numpy.ndarray

In [ ]:
Y= data.iloc[:,4].values
#Y

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le_y= LabelEncoder()


In [ ]:
Y= le_y.fit_transform(Y)

In [ ]:
#Y

In [ ]:
#split the dataset
# Import Library for splitting data
from sklearn.model_selection import train_test_split

In [ ]:
# Creating Train and Test datasets
X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size = 0.25)

In [ ]:
# Creating Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()
clf.fit(X_train,y_train)

DecisionTreeClassifier()

In [ ]:
# Predict Y.
y_pred = clf.predict(X_test)

In [ ]:
y_pred

array([2, 0, 2, 0, 1, 0, 2, 1, 0, 0, 0, 1, 2, 2, 0, 0, 0, 2, 0, 0, 0, 2,
       2, 2, 2, 1, 1, 0, 2, 2, 2, 0, 2, 1, 1, 1, 0, 1])

In [ ]:
print("Train data accuracy:",accuracy_score(y_true = y_train, y_pred=clf.predict(X_train)))

Train data accuracy: 1.0


In [ ]:
print("Test data accuracy:",accuracy_score(y_true = y_test, y_pred=y_pred))


Test data accuracy: 0.9210526315789473


In [ ]:
from sklearn.ensemble import RandomForestRegressor
rfr = RandomForestRegressor()
rfr.fit(X_train, y_train)
y_pred = rfr.predict(X_test)

In [ ]:
y_pred

array([2.  , 0.  , 2.  , 0.  , 1.1 , 0.  , 1.99, 1.  , 0.  , 0.  , 0.  ,
       1.  , 2.  , 2.  , 0.  , 0.  , 0.  , 1.99, 0.  , 0.  , 0.  , 2.  ,
       2.  , 2.  , 1.98, 1.  , 1.  , 0.  , 2.  , 1.99, 2.  , 0.  , 2.  ,
       1.09, 1.  , 1.11, 0.  , 1.  ])