<a href="https://colab.research.google.com/github/dineshkalal/ML/blob/main/LinearReg_Iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [45]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [41]:
#Linear Regression Model


In [46]:
df= sns.load_dataset('iris')
#df = pd.read_csv('iris')
print(df)


X= df.iloc[: , :-1].values
print(X)
Y= df.iloc[:,-1:].values
print(Y)


     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0

In [43]:
from sklearn.preprocessing import LabelEncoder

In [47]:
    le_y= LabelEncoder()
    Y=le_y.fit_transform(Y)
    print(Y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [48]:
from sklearn.model_selection import train_test_split    #the tool for split the data
from sklearn.linear_model import  LinearRegression      #and because we know we going to use linear regression for our prediction we import the class as well


#over here we split the data. into the x&y trainer and y&x tester
X_train,X_test,y_train,y_test = train_test_split(X,Y, test_size = 0.20)

In [49]:
X_train

array([[6.1, 2.8, 4.7, 1.2],
       [5. , 2. , 3.5, 1. ],
       [5.1, 3.5, 1.4, 0.3],
       [4.7, 3.2, 1.6, 0.2],
       [5.5, 2.4, 3.7, 1. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.6, 2.5, 3.9, 1.1],
       [5. , 3. , 1.6, 0.2],
       [5.9, 3. , 5.1, 1.8],
       [6.1, 2.6, 5.6, 1.4],
       [6.5, 3.2, 5.1, 2. ],
       [4.6, 3.2, 1.4, 0.2],
       [6.5, 3. , 5.5, 1.8],
       [4.9, 2.5, 4.5, 1.7],
       [6.8, 2.8, 4.8, 1.4],
       [5.7, 2.5, 5. , 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.1, 3. , 4.6, 1.4],
       [6.6, 3. , 4.4, 1.4],
       [6.1, 2.9, 4.7, 1.4],
       [6.1, 2.8, 4. , 1.3],
       [5. , 3.6, 1.4, 0.2],
       [5.1, 3.8, 1.6, 0.2],
       [7.2, 3.6, 6.1, 2.5],
       [5.2, 3.4, 1.4, 0.2],
       [6.2, 2.2, 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [5.5, 2.6, 4.4, 1.2],
       [6.7, 3.1, 4.7, 1.5],
       [4.9, 3. , 1.4, 0.2],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.5, 1.3, 0.3],
       [5.6, 2.7, 4.2, 1.3],
       [4.9, 3.6, 1.4, 0.1],
       [5.5, 3

In [50]:
y_train

array([1, 1, 0, 0, 1, 2, 1, 0, 2, 2, 2, 0, 2, 2, 1, 2, 2, 1, 1, 1, 1, 0,
       0, 2, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 2, 0, 0, 2, 2, 0, 1, 2,
       1, 1, 1, 1, 0, 0, 0, 2, 0, 0, 1, 0, 0, 1, 1, 0, 2, 0, 0, 2, 1, 0,
       2, 2, 2, 2, 2, 2, 2, 2, 1, 0, 0, 2, 2, 1, 1, 0, 2, 2, 2, 1, 0, 2,
       2, 0, 0, 0, 1, 2, 0, 2, 0, 1, 2, 1, 1, 0, 1, 2, 2, 1, 2, 1, 1, 0,
       0, 1, 0, 0, 2, 2, 1, 2, 2, 1])

In [ ]:
lr = LinearRegression()        #create our linear model

#fitting the model on the training data and try to predict the X_test
iris_model = lr.fit(X_train, y_train)
predictions = iris_model.predict(X_test)

In [ ]:
print(predictions)
print(y_test)

In [ ]:


from sklearn.metrics import r2_score   #class will help us to calculate and see the score of our predictions

r2_score(y_test, predictions)

