In [ ]:
#sklearn- Lab1
# Linear Regression Model

In [1]:
import pandas as pd
import numpy as np

In [2]:
df= pd.read_csv('iris.csv')
df

sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [3]:
#y=ax+c
#:rain #testing   supervised ML
#80:20
df['variety'].value_counts()

Setosa        50
Versicolor    50
Virginica     50
Name: variety, dtype: int64

In [4]:
x=df.iloc[:,0:4].values # filter Independent variable

In [6]:
y=df.iloc[:,4].values  # filter dependent variable



In [7]:
#convert Y in numbers encoding

In [8]:
from sklearn.preprocessing import LabelEncoder

In [9]:
labelencoder_y= LabelEncoder()

In [10]:
y=labelencoder_y.fit_transform(y)

In [12]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [13]:
from sklearn.model_selection import train_test_split 


In [14]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [15]:
x_train

array([[6.5, 3. , 5.5, 1.8],
       [7. , 3.2, 4.7, 1.4],
       [6.5, 3. , 5.2, 2. ],
       [4.4, 2.9, 1.4, 0.2],
       [7.7, 3.8, 6.7, 2.2],
       [5.9, 3. , 5.1, 1.8],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 2.7, 4.9, 1.8],
       [5.6, 3. , 4.5, 1.5],
       [5.2, 3.4, 1.4, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [7.3, 2.9, 6.3, 1.8],
       [6.1, 2.9, 4.7, 1.4],
       [4.4, 3. , 1.3, 0.2],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [4.6, 3.1, 1.5, 0.2],
       [6.3, 3.3, 6. , 2.5],
       [6.4, 3.2, 4.5, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.9, 3.1, 4.9, 1.5],
       [5.1, 3.8, 1.6, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [5.1, 3.5, 1.4, 0.2],
       [5.6, 2.7, 4.2, 1.3],
       [5.8, 2.7, 5.1, 1.9],
       [5.8, 2.8, 5.1, 2.4],
       [6.9, 3.1, 5.4, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [6.3, 2.5, 5. , 1.9],
       [5.1, 3.8, 1.9, 0.4],
       [7.7, 2.8, 6.7, 2. ],
       [5.8, 2.7, 4.1, 1. ],
       [5.5, 4.2, 1.4, 0.2],
       [6.7, 3

In [16]:
x_train.size

420

In [17]:
x_test.size

180

In [18]:
y_train.size

105

In [19]:
y_test.size

45

In [20]:
from sklearn.linear_model import LogisticRegression

In [21]:
logmodel=LogisticRegression()
logmodel.fit(x_train,y_train)

/home/administrato/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [23]:
y_pred= logmodel.predict(x_test)

In [24]:
y_pred
np.sort(y_pred)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2])

In [25]:
y_test
np.sort(y_test)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2])

In [26]:
from sklearn.metrics import confusion_matrix

In [27]:
confusion_matrix(y_test,y_pred)

array([[17,  0,  0],
       [ 0, 14,  0],
       [ 0,  0, 14]])

In [28]:
(28/30)*100

93.33333333333333

In [29]:
logmodel.score(x_test,y_test)

1.0

In [31]:
from sklearn.neighbors import KNeighborsClassifier  


In [32]:
classifier_knn= KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2) # distance name

In [33]:
classifier_knn.fit(x_train,y_train) # model training 70:30

KNeighborsClassifier()

In [49]:
y_pred_knn=classifier_knn.predict(x_test)

In [36]:
y_pred_knn

array([1, 2, 0, 1, 1, 0, 2, 2, 0, 2, 0, 0, 0, 2, 0, 2, 1, 0, 2, 2, 0, 2,
       0, 1, 2, 0, 2, 2, 1, 1, 1, 0, 2, 0, 0, 2, 1, 1, 1, 0, 1, 0, 1, 2,
       0])

In [37]:
from sklearn.metrics import confusion_matrix

In [38]:
confusion_matrix(y_test,y_pred_knn)

array([[17,  0,  0],
       [ 0, 13,  1],
       [ 0,  0, 14]])

In [39]:
classifier_knn.score(x_test,y_test)

0.9777777777777777

In [40]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred_knn,y_test)

0.9777777777777777

In [41]:
# NaiveBias Model

In [43]:
from sklearn.naive_bayes import GaussianNB

In [45]:
classifier_nb= GaussianNB()

In [46]:
classifier_nb.fit(x_train,y_train)

GaussianNB()

In [50]:
y_pred= classifier_nb.predict(x_test)

In [51]:
y_pred

array([1, 2, 0, 1, 1, 0, 2, 2, 0, 2, 0, 0, 0, 1, 0, 2, 1, 0, 1, 2, 0, 2,
       0, 1, 2, 0, 2, 2, 1, 1, 1, 0, 2, 0, 0, 2, 1, 1, 1, 0, 1, 0, 1, 2,
       0])

In [52]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred_knn,y_test)

0.9777777777777777

In [53]:
confusion_matrix(y_test,y_pred)

array([[17,  0,  0],
       [ 0, 14,  0],
       [ 0,  1, 13]])

In [54]:
classifier_nb.score(x_test,y_test)

0.9777777777777777